// generated by newgenasym  Mon Jan 31 14:07:28 2022


module ren_r7fa8d1bh2a_rev2_10 (avcc0, avcc_mipi, avcc_usbhs, avss0, mipi_cl_n, mipi_cl_p,
        mipi_dl0_n, mipi_dl0_p, mipi_dl1_n, mipi_dl1_p, p000, p001,
        p002, p003, p004, p005, p006, p007, p008, p009, p010, p011,
        p014, p015, p100, p101, p102, p103, p104, p105, p106, p107,
        p112, p113, p114, p115, p200, \p201/md , p206, p207, \p208/tdi ,
        \p209/tdo , \p210/tms/swdio , \p211/tck/swclk , \p212/extal ,
        \p213/xtal , p300, p301, p302, p303, p304, p305, p306, p307,
        p308, p309, p310, p311, p312, p400, p401, p402, p403, p404,
        p405, \p406/excin , p407, p408, p409, p410, p411, p412, p413,
        p414, p415, p500, p501, p502, p503, p504, p505, p506, p507,
        p508, p509, p510, p511, p512, p513, p514, p515, p600, p601,
        p602, p603, p604, p605, p606, p607, p609, p610, p611, p612,
        p613, p614, p615, p700, p701, p702, p703, p704, p705, p706,
        p707, p708, p709, p710, p711, p712, p713, p714, p715, p800,
        p801, p802, p803, p804, p805, p806, p807, p808, p809, p810,
        p811, p812, p813, \p814/usb_dp , \p815/usb_dm , p902, p903, p904,
        p905, p906, p907, p908, p909, p910, p911, p912, p913, p914,
        p915, pa00, pa01, pa02, pa03, pa04, pa05, pa06, pa07, pa08,
        pa09, pa10, pa11, pa12, pa13, pa14, pa15, pb00, pb01, pb02,
        pb03, pb04, pb05, pb06, pb07, res, usbhs_dm, usbhs_dp,
        usbhs_rref, vbatt, vcc, vcc18_mipi, vcc2, vcc_dcdc, vcc_usb,
        vcc_usbhs, vcl, vlo, vrefh, vrefh0, vrefl, vrefl0, vss,
        vss1_usbhs, vss2_usbhs, vss_dcdc, vss_mipi, vss_usb, xcin,
        xcout);
    input avcc0;
    input avcc_mipi;
    input avcc_usbhs;
    input avss0;
    output mipi_cl_n;
    output mipi_cl_p;
    output mipi_dl0_n;
    output mipi_dl0_p;
    output mipi_dl1_n;
    output mipi_dl1_p;
    inout p000;
    inout p001;
    inout p002;
    inout p003;
    inout p004;
    inout p005;
    inout p006;
    inout p007;
    inout p008;
    inout p009;
    inout p010;
    inout p011;
    inout p014;
    inout p015;
    inout p100;
    inout p101;
    inout p102;
    inout p103;
    inout p104;
    inout p105;
    inout p106;
    inout p107;
    inout p112;
    inout p113;
    inout p114;
    inout p115;
    inout p200;
    inout \p201/md ;
    inout p206;
    inout p207;
    inout \p208/tdi ;
    inout \p209/tdo ;
    inout \p210/tms/swdio ;
    inout \p211/tck/swclk ;
    inout \p212/extal ;
    inout \p213/xtal ;
    inout p300;
    inout p301;
    inout p302;
    inout p303;
    inout p304;
    inout p305;
    inout p306;
    inout p307;
    inout p308;
    inout p309;
    inout p310;
    inout p311;
    inout p312;
    inout p400;
    inout p401;
    inout p402;
    inout p403;
    inout p404;
    inout p405;
    inout \p406/excin ;
    inout p407;
    inout p408;
    inout p409;
    inout p410;
    inout p411;
    inout p412;
    inout p413;
    inout p414;
    inout p415;
    inout p500;
    inout p501;
    inout p502;
    inout p503;
    inout p504;
    inout p505;
    inout p506;
    inout p507;
    inout p508;
    inout p509;
    inout p510;
    inout p511;
    inout p512;
    inout p513;
    inout p514;
    inout p515;
    inout p600;
    inout p601;
    inout p602;
    inout p603;
    inout p604;
    inout p605;
    inout p606;
    inout p607;
    inout p609;
    inout p610;
    inout p611;
    inout p612;
    inout p613;
    inout p614;
    inout p615;
    inout p700;
    inout p701;
    inout p702;
    inout p703;
    inout p704;
    inout p705;
    inout p706;
    inout p707;
    inout p708;
    inout p709;
    inout p710;
    inout p711;
    inout p712;
    inout p713;
    inout p714;
    inout p715;
    inout p800;
    inout p801;
    inout p802;
    inout p803;
    inout p804;
    inout p805;
    inout p806;
    inout p807;
    inout p808;
    inout p809;
    inout p810;
    inout p811;
    inout p812;
    inout p813;
    inout \p814/usb_dp ;
    inout \p815/usb_dm ;
    inout p902;
    inout p903;
    inout p904;
    inout p905;
    inout p906;
    inout p907;
    inout p908;
    inout p909;
    inout p910;
    inout p911;
    inout p912;
    inout p913;
    inout p914;
    inout p915;
    inout pa00;
    inout pa01;
    inout pa02;
    inout pa03;
    inout pa04;
    inout pa05;
    inout pa06;
    inout pa07;
    inout pa08;
    inout pa09;
    inout pa10;
    inout pa11;
    inout pa12;
    inout pa13;
    inout pa14;
    inout pa15;
    inout pb00;
    inout pb01;
    inout pb02;
    inout pb03;
    inout pb04;
    inout pb05;
    inout pb06;
    inout pb07;
    input res;
    inout usbhs_dm;
    inout usbhs_dp;
    inout usbhs_rref;
    input vbatt;
    input [5:0] vcc;
    input vcc18_mipi;
    input [1:0] vcc2;
    input [1:0] vcc_dcdc;
    input vcc_usb;
    input vcc_usbhs;
    input [5:0] vcl;
    input [1:0] vlo;
    input vrefh;
    input vrefh0;
    input vrefl;
    input vrefl0;
    input [10:0] vss;
    input vss1_usbhs;
    input vss2_usbhs;
    input vss_dcdc;
    input vss_mipi;
    input vss_usb;
    input xcin;
    output xcout;


    initial
        begin
        end

endmodule
