-- generated by newgenasym Thu Feb 27 15:26:05 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity rubber_foot is
    port (    
	\1\:       INOUT  STD_LOGIC);
end rubber_foot;
