// generated by newgenasym  Mon Mar 10 13:42:58 2014


module mur_dlp11 (pin1, pin2, pin3, pin4);
    inout pin1;
    inout pin2;
    inout pin3;
    inout pin4;


    initial
        begin
        end

endmodule
