-- generated by newgenasym Mon Mar 10 13:42:58 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mur_dlp11 is
    port (    
	PIN1:      INOUT  STD_LOGIC;    
	PIN2:      INOUT  STD_LOGIC;    
	PIN3:      INOUT  STD_LOGIC;    
	PIN4:      INOUT  STD_LOGIC);
end mur_dlp11;
