// generated by newgenasym  Wed Dec  9 16:41:54 2020


module res4s (a, b);
    parameter    size = 1;
    inout [size-1:0] a;
    inout [size-1:0] b;


    initial
        begin
        end

endmodule
