-- generated by newgenasym Wed Dec  9 16:41:54 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity res4s is
    generic (
        size:positive:= 1
            );
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	B:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end res4s;
