// generated by newgenasym  Wed Apr 25 16:26:26 2012


module single_row_4 (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
