// generated by newgenasym  Tue Feb 11 14:09:57 2020


module dio_ap2151 (en, flg, gnd, in, out);
    output en;
    input flg;
    input gnd;
    input in;
    output out;


    initial
        begin
        end

endmodule
