-- generated by newgenasym Tue Feb 11 14:09:57 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity dio_ap2151 is
    port (    
	EN:        OUT    STD_LOGIC;    
	FLG:       IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC);
end dio_ap2151;
