-- generated by newgenasym Fri Aug 03 13:51:34 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tvsdiode is
    port (    
	A:         INOUT  STD_LOGIC;    
	C:         INOUT  STD_LOGIC);
end tvsdiode;
