// generated by newgenasym  Wed Aug 25 16:06:52 2021


module ecs_ecs_1612mv (clk, gnd, stb, vcc);
    output clk;
    input gnd;
    input stb;
    input vcc;


    initial
        begin
        end

endmodule
