-- generated by newgenasym Wed Aug 25 16:06:52 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ecs_ecs_1612mv is
    port (    
	CLK:       OUT    STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	STB:       IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end ecs_ecs_1612mv;
