// generated by newgenasym  Thu Aug 22 16:12:41 2019


module ren_isl9008 (en, gnd, nc, vin, vo);
    input en;
    input gnd;
    inout nc;
    input vin;
    output vo;


    initial
        begin
        end

endmodule
