-- generated by newgenasym Thu Aug 22 16:12:41 2019

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ren_isl9008 is
    port (    
	EN:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	VIN:       IN     STD_LOGIC;    
	VO:        OUT    STD_LOGIC);
end ren_isl9008;
