-- generated by newgenasym Mon Jul 02 18:05:00 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity led is
    port (    
	A:         INOUT  STD_LOGIC;    
	K:         INOUT  STD_LOGIC);
end led;
