-- generated by newgenasym Thu Jun 14 09:58:20 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity cappol is
    port (    
	N:         INOUT  STD_LOGIC;    
	P:         INOUT  STD_LOGIC);
end cappol;
