// generated by newgenasym  Mon Jul 02 14:48:36 2018


module crystal_fa_xxx (pin1, pin2, pin3, pin4);
    inout pin1;
    inout pin2;
    inout pin3;
    inout pin4;


    initial
        begin
        end

endmodule
