-- generated by newgenasym Mon Jul 02 14:48:36 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity crystal_fa_xxx is
    port (    
	PIN1:      INOUT  STD_LOGIC;    
	PIN2:      INOUT  STD_LOGIC;    
	PIN3:      INOUT  STD_LOGIC;    
	PIN4:      INOUT  STD_LOGIC);
end crystal_fa_xxx;
