// generated by newgenasym  Thu Feb 27 13:37:31 2020


module rclamp0582n (gnd, io1, io2, nc, vbus);
    input gnd;
    inout io1;
    inout io2;
    inout [1:0] nc;
    input vbus;


    initial
        begin
        end

endmodule
