-- generated by newgenasym Thu Feb 27 13:37:31 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity RCLAMP0582N is
    port (    
	GND:       IN     STD_LOGIC;    
	IO1:       INOUT  STD_LOGIC;    
	IO2:       INOUT  STD_LOGIC;    
	NC:        INOUT  STD_LOGIC_VECTOR (1 DOWNTO 0);    
	VBUS:      IN     STD_LOGIC);
end RCLAMP0582N;
