-- generated by newgenasym Tue Mar  9 08:34:20 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity cap is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end cap;
