-- generated by newgenasym Thu Jan 13 17:07:48 2022

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity single_row_2 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end single_row_2;
