-- generated by newgenasym Fri May 11 09:38:27 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity crystal is
    port (    
	PIN1:      INOUT  STD_LOGIC;    
	PIN2:      INOUT  STD_LOGIC);
end crystal;
