// generated by newgenasym  Mon Apr 23 16:56:55 2012


module but_4pin (pin1, pin2, pin3, pin4);
    inout pin1;
    inout pin2;
    inout pin3;
    inout pin4;


    initial
        begin
        end

endmodule
