-- generated by newgenasym Mon Apr 23 16:56:55 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity but_4pin is
    port (    
	PIN1:      INOUT  STD_LOGIC;    
	PIN2:      INOUT  STD_LOGIC;    
	PIN3:      INOUT  STD_LOGIC;    
	PIN4:      INOUT  STD_LOGIC);
end but_4pin;
