// generated by newgenasym  Fri Jan 21 11:00:14 2022


module busswitchquad (\1a , \1b1 , \1b2 , \2a , \2b1 , \2b2 , \3a , \3b1 , \3b2 , \4a , \4b1 , \4b2 , expad,
        gnd, oe, s, vcc);
    inout \1a ;
    inout \1b1 ;
    inout \1b2 ;
    inout \2a ;
    inout \2b1 ;
    inout \2b2 ;
    inout \3a ;
    inout \3b1 ;
    inout \3b2 ;
    inout \4a ;
    inout \4b1 ;
    inout \4b2 ;
    inout expad;
    input gnd;
    input oe;
    input s;
    input vcc;


    initial
        begin
        end

endmodule
