-- generated by newgenasym Fri Jan 21 11:00:14 2022

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity busswitchquad is
    port (    
	\1a\:      INOUT  STD_LOGIC;    
	\1b1\:     INOUT  STD_LOGIC;    
	\1b2\:     INOUT  STD_LOGIC;    
	\2a\:      INOUT  STD_LOGIC;    
	\2b1\:     INOUT  STD_LOGIC;    
	\2b2\:     INOUT  STD_LOGIC;    
	\3a\:      INOUT  STD_LOGIC;    
	\3b1\:     INOUT  STD_LOGIC;    
	\3b2\:     INOUT  STD_LOGIC;    
	\4a\:      INOUT  STD_LOGIC;    
	\4b1\:     INOUT  STD_LOGIC;    
	\4b2\:     INOUT  STD_LOGIC;    
	EXPAD:     INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	OE:        IN     STD_LOGIC;    
	S:         IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end busswitchquad;
