-- generated by newgenasym Fri May 04 13:48:41 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity dio is
    port (    
	A:         INOUT  STD_LOGIC;    
	K:         INOUT  STD_LOGIC);
end dio;
