// generated by newgenasym  Wed Feb  1 14:23:40 2023


module busswitch (a1, a2, a3, a4, a5, a6, a7, a8, b1, b2, b3, b4, b5, b6, b7, b8,
        expad, gnd, nc, oe, vcc);
    inout a1;
    inout a2;
    inout a3;
    inout a4;
    inout a5;
    inout a6;
    inout a7;
    inout a8;
    inout b1;
    inout b2;
    inout b3;
    inout b4;
    inout b5;
    inout b6;
    inout b7;
    inout b8;
    inout expad;
    input gnd;
    inout nc;
    input oe;
    input vcc;


    initial
        begin
        end

endmodule
