-- generated by newgenasym Wed Feb  1 14:23:40 2023

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity busswitch is
    port (    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	A3:        INOUT  STD_LOGIC;    
	A4:        INOUT  STD_LOGIC;    
	A5:        INOUT  STD_LOGIC;    
	A6:        INOUT  STD_LOGIC;    
	A7:        INOUT  STD_LOGIC;    
	A8:        INOUT  STD_LOGIC;    
	B1:        INOUT  STD_LOGIC;    
	B2:        INOUT  STD_LOGIC;    
	B3:        INOUT  STD_LOGIC;    
	B4:        INOUT  STD_LOGIC;    
	B5:        INOUT  STD_LOGIC;    
	B6:        INOUT  STD_LOGIC;    
	B7:        INOUT  STD_LOGIC;    
	B8:        INOUT  STD_LOGIC;    
	EXPAD:     INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	OE:        IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end busswitch;
