// generated by newgenasym  Thu Jan 27 10:46:42 2022


module ren_ra4m2 (avcc0, \avss0/vrefl , p000, p001, p002, p013, p014, p015, p100,
        p101, p102, p103, p104, \p108/tms/swdio , \p109/tdo/swo ,
        \p110/tdi , p111, p112, p200, \p201/md , p206, p207, \p212/extal ,
        \p213/xtal , \p300/tck/swclk , p301, p302, p402, p407, p408,
        p409, p500, res, usb_dm, usb_dp, vbatt, vcc, vcc_usb, vcl,
        vrefh, vrefh0, vrefl0, vss, vss_usb, xcin, xcout);
    input avcc0;
    input \avss0/vrefl ;
    inout p000;
    inout p001;
    inout p002;
    inout p013;
    inout p014;
    inout p015;
    inout p100;
    inout p101;
    inout p102;
    inout p103;
    inout p104;
    inout \p108/tms/swdio ;
    inout \p109/tdo/swo ;
    inout \p110/tdi ;
    inout p111;
    inout p112;
    inout p200;
    inout \p201/md ;
    inout p206;
    inout p207;
    inout \p212/extal ;
    inout \p213/xtal ;
    inout \p300/tck/swclk ;
    inout p301;
    inout p302;
    inout p402;
    inout p407;
    inout p408;
    inout p409;
    inout p500;
    input res;
    inout usb_dm;
    inout usb_dp;
    input vbatt;
    input [1:0] vcc;
    input vcc_usb;
    input vcl;
    input vrefh;
    inout vrefh0;
    inout vrefl0;
    input [1:0] vss;
    input vss_usb;
    input xcin;
    output xcout;


    initial
        begin
        end

endmodule
