-- generated by newgenasym Wed Dec  9 16:03:03 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity res is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end res;
