// generated by newgenasym  Mon Oct 26 07:41:30 2020


module crystal_abm8_xx (pin1, pin2, pin3, pin4);
    inout pin1;
    input pin2;
    inout pin3;
    input pin4;


    initial
        begin
        end

endmodule
