-- generated by newgenasym Mon Oct 26 07:41:30 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity crystal_abm8_xx is
    port (    
	PIN1:      INOUT  STD_LOGIC;    
	PIN2:      IN     STD_LOGIC;    
	PIN3:      INOUT  STD_LOGIC;    
	PIN4:      IN     STD_LOGIC);
end crystal_abm8_xx;
