// generated by newgenasym  Mon Apr 23 17:15:29 2012


module sw_dip8 (pin1, pin10, pin11, pin12, pin13, pin14, pin15, pin16, pin2,
        pin3, pin4, pin5, pin6, pin7, pin8, pin9);
    inout pin1;
    inout pin10;
    inout pin11;
    inout pin12;
    inout pin13;
    inout pin14;
    inout pin15;
    inout pin16;
    inout pin2;
    inout pin3;
    inout pin4;
    inout pin5;
    inout pin6;
    inout pin7;
    inout pin8;
    inout pin9;


    initial
        begin
        end

endmodule
