// generated by newgenasym  Tue Jan 28 10:52:27 2020


module micro_usb_a_b (dm, dp, gnd, id, shield, vbus);
    inout dm;
    inout dp;
    input gnd;
    inout id;
    input [5:0] shield;
    inout vbus;


    initial
        begin
        end

endmodule
