-- generated by newgenasym Tue Jan 28 10:52:27 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity micro_usb_a_b is
    port (    
	DM:        INOUT  STD_LOGIC;    
	DP:        INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	ID:        INOUT  STD_LOGIC;    
	SHIELD:    IN     STD_LOGIC_VECTOR (5 DOWNTO 0);    
	VBUS:      INOUT  STD_LOGIC);
end micro_usb_a_b;
