-- generated by newgenasym Wed Jul 17 10:03:49 2019

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ind is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end ind;
