// generated by newgenasym  Thu Apr 19 07:59:28 2012


module rj45_con_j0 (ct_rd, ct_td, gnd, gnd_h1, gnd_h2, gr_an, gr_ka, nc1,
        rdminus, rdplus, tdminus, tdplus, ye_an, ye_ka);
    inout ct_rd;
    inout ct_td;
    inout gnd;
    inout gnd_h1;
    inout gnd_h2;
    inout gr_an;
    inout gr_ka;
    inout nc1;
    inout rdminus;
    inout rdplus;
    inout tdminus;
    inout tdplus;
    inout ye_an;
    inout ye_ka;


    initial
        begin
        end

endmodule
