-- generated by newgenasym Thu Apr 19 07:59:28 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity rj45_con_j0 is
    port (    
	CT_RD:     INOUT  STD_LOGIC;    
	CT_TD:     INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	GND_H1:    INOUT  STD_LOGIC;    
	GND_H2:    INOUT  STD_LOGIC;    
	GR_AN:     INOUT  STD_LOGIC;    
	GR_KA:     INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	RDMINUS:   INOUT  STD_LOGIC;    
	RDPLUS:    INOUT  STD_LOGIC;    
	TDMINUS:   INOUT  STD_LOGIC;    
	TDPLUS:    INOUT  STD_LOGIC;    
	YE_AN:     INOUT  STD_LOGIC;    
	YE_KA:     INOUT  STD_LOGIC);
end rj45_con_j0;
