// generated by newgenasym  Thu Jan 30 11:19:49 2020


module int_isl8010x (dnc, enable, epad, gnd, pg, \sense/adj , ss, vin, vout);
    inout dnc;
    inout enable;
    input epad;
    input gnd;
    inout pg;
    inout \sense/adj ;
    inout ss;
    input [1:0] vin;
    input [1:0] vout;


    initial
        begin
        end

endmodule
