-- generated by newgenasym Thu Jan 30 11:19:50 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity int_isl8010x is
    port (    
	DNC:       INOUT  STD_LOGIC;    
	ENABLE:    INOUT  STD_LOGIC;    
	EPAD:      IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	PG:        INOUT  STD_LOGIC;    
	\sense/adj\: INOUT  STD_LOGIC;    
	SS:        INOUT  STD_LOGIC;    
	VIN:       IN     STD_LOGIC_VECTOR (1 DOWNTO 0);    
	VOUT:      IN     STD_LOGIC_VECTOR (1 DOWNTO 0));
end int_isl8010x;
