-- generated by newgenasym Mon Feb 10 08:58:52 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity scraper_bridge is
    port (    
	PIN1:      INOUT  STD_LOGIC;    
	PIN2:      INOUT  STD_LOGIC);
end scraper_bridge;
