// generated by newgenasym  Wed Aug 11 10:24:12 2021


module ren_ics1894_32 (\amdix/rxd3 , \ansel/rxclk , \fdpx/rxd0 , mdc, mdio, \nod/rxer ,
        \p0/led0 , \p1/iso/led1 , \p2/int , \p3/rxd2 , paddle, refin,
        refout, reset_n, \rmii/rxdv , \rxtri/rxd1 , \speed/txclk , tcsr,
        tp_an, tp_ap, tp_bn, tp_bp, txd0, txd1, txd2, txd3, txen,
        vdd_0, vdd_1, vddd, vddio, vss_0, vss_1);
    inout \amdix/rxd3 ;
    inout \ansel/rxclk ;
    inout \fdpx/rxd0 ;
    input mdc;
    inout mdio;
    inout \nod/rxer ;
    inout \p0/led0 ;
    inout \p1/iso/led1 ;
    inout \p2/int ;
    inout \p3/rxd2 ;
    input paddle;
    input refin;
    output refout;
    input reset_n;
    inout \rmii/rxdv ;
    inout \rxtri/rxd1 ;
    inout \speed/txclk ;
    inout tcsr;
    inout tp_an;
    inout tp_ap;
    inout tp_bn;
    inout tp_bp;
    input txd0;
    input txd1;
    input txd2;
    input txd3;
    input txen;
    input vdd_0;
    input vdd_1;
    input vddd;
    input vddio;
    input vss_0;
    input vss_1;


    initial
        begin
        end

endmodule
