-- generated by newgenasym Wed Aug 11 10:24:12 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ren_ics1894_32 is
    port (    
	\amdix/rxd3\: INOUT  STD_LOGIC;    
	\ansel/rxclk\: INOUT  STD_LOGIC;    
	\fdpx/rxd0\: INOUT  STD_LOGIC;    
	MDC:       IN     STD_LOGIC;    
	MDIO:      INOUT  STD_LOGIC;    
	\nod/rxer\: INOUT  STD_LOGIC;    
	\p0/led0\: INOUT  STD_LOGIC;    
	\p1/iso/led1\: INOUT  STD_LOGIC;    
	\p2/int\:  INOUT  STD_LOGIC;    
	\p3/rxd2\: INOUT  STD_LOGIC;    
	PADDLE:    IN     STD_LOGIC;    
	REFIN:     IN     STD_LOGIC;    
	REFOUT:    OUT    STD_LOGIC;    
	RESET_N:   IN     STD_LOGIC;    
	\rmii/rxdv\: INOUT  STD_LOGIC;    
	\rxtri/rxd1\: INOUT  STD_LOGIC;    
	\speed/txclk\: INOUT  STD_LOGIC;    
	TCSR:      INOUT  STD_LOGIC;    
	TP_AN:     INOUT  STD_LOGIC;    
	TP_AP:     INOUT  STD_LOGIC;    
	TP_BN:     INOUT  STD_LOGIC;    
	TP_BP:     INOUT  STD_LOGIC;    
	TXD0:      IN     STD_LOGIC;    
	TXD1:      IN     STD_LOGIC;    
	TXD2:      IN     STD_LOGIC;    
	TXD3:      IN     STD_LOGIC;    
	TXEN:      IN     STD_LOGIC;    
	VDD_0:     IN     STD_LOGIC;    
	VDD_1:     IN     STD_LOGIC;    
	VDDD:      IN     STD_LOGIC;    
	VDDIO:     IN     STD_LOGIC;    
	VSS_0:     IN     STD_LOGIC;    
	VSS_1:     IN     STD_LOGIC);
end ren_ics1894_32;
