-- generated by newgenasym Wed Apr 25 16:29:41 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity single_row_6 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC);
end single_row_6;
