-- generated by newgenasym Fri May 04 13:47:44 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity schotdio is
    port (    
	A:         INOUT  STD_LOGIC;    
	K:         INOUT  STD_LOGIC);
end schotdio;
