// generated by newgenasym  Tue Jan 28 13:19:51 2020


module micro_usb_b_9pin (dm, dp, gnd, id, shield, vbus);
    inout dm;
    inout dp;
    input gnd;
    inout id;
    input [3:0] shield;
    inout vbus;


    initial
        begin
        end

endmodule
