-- generated by newgenasym Tue Jan 28 13:19:51 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity micro_usb_b_9pin is
    port (    
	DM:        INOUT  STD_LOGIC;    
	DP:        INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	ID:        INOUT  STD_LOGIC;    
	SHIELD:    IN     STD_LOGIC_VECTOR (3 DOWNTO 0);    
	VBUS:      INOUT  STD_LOGIC);
end micro_usb_b_9pin;
