-- generated by newgenasym Thu Dec  8 09:56:14 2022

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity dio_tvs is
    port (    
	PIN1:      INOUT  STD_LOGIC;    
	PIN2:      INOUT  STD_LOGIC);
end dio_tvs;
