// generated by newgenasym  Fri Feb  4 09:41:30 2022


module issi512mbsdram_x16 (a0, a1, a10, a11, a12, a2, a3, a4, a5, a6, a7, a8, a9, ba0, ba1,
        cas, cke, clk, cs, dq0, dq1, dq10, dq11, dq12, dq13, dq14, dq15,
        dq2, dq3, dq4, dq5, dq6, dq7, dq8, dq9, dqmh, dqml, nc, ras, vdd,
        vddq, vss, vssq, we);
    input a0;
    input a1;
    input a10;
    input a11;
    input a12;
    input a2;
    input a3;
    input a4;
    input a5;
    input a6;
    input a7;
    input a8;
    input a9;
    input ba0;
    input ba1;
    input cas;
    input cke;
    input clk;
    input cs;
    inout dq0;
    inout dq1;
    inout dq10;
    inout dq11;
    inout dq12;
    inout dq13;
    inout dq14;
    inout dq15;
    inout dq2;
    inout dq3;
    inout dq4;
    inout dq5;
    inout dq6;
    inout dq7;
    inout dq8;
    inout dq9;
    inout dqmh;
    inout dqml;
    inout nc;
    input ras;
    input [2:0] vdd;
    input [3:0] vddq;
    input [2:0] vss;
    input [3:0] vssq;
    input we;


    initial
        begin
        end

endmodule
