// generated by newgenasym  Mon Jul  3 14:14:18 2023


module s28hl512tfpbhi010 (ck, \cs# , dnu, dq0, dq1, dq2, dq3, dq4, dq5, dq6, dq7, ds, \int# ,
        \reset# , vcc, vccq, vss, vssq);
    input ck;
    input \cs# ;
    inout [4:0] dnu;
    inout dq0;
    inout dq1;
    inout dq2;
    inout dq3;
    inout dq4;
    inout dq5;
    inout dq6;
    inout dq7;
    output ds;
    output \int# ;
    input \reset# ;
    input vcc;
    input [1:0] vccq;
    input vss;
    input [1:0] vssq;


    initial
        begin
        end

endmodule
