-- generated by newgenasym Mon Jul  3 14:14:18 2023

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity S28HL512TFPBHI010 is
    port (    
	CK:        IN     STD_LOGIC;    
	\cs#\:     IN     STD_LOGIC;    
	DNU:       INOUT  STD_LOGIC_VECTOR (4 DOWNTO 0);    
	DQ0:       INOUT  STD_LOGIC;    
	DQ1:       INOUT  STD_LOGIC;    
	DQ2:       INOUT  STD_LOGIC;    
	DQ3:       INOUT  STD_LOGIC;    
	DQ4:       INOUT  STD_LOGIC;    
	DQ5:       INOUT  STD_LOGIC;    
	DQ6:       INOUT  STD_LOGIC;    
	DQ7:       INOUT  STD_LOGIC;    
	DS:        OUT    STD_LOGIC;    
	\int#\:    OUT    STD_LOGIC;    
	\reset#\:  IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	VCCQ:      IN     STD_LOGIC_VECTOR (1 DOWNTO 0);    
	VSS:       IN     STD_LOGIC;    
	VSSQ:      IN     STD_LOGIC_VECTOR (1 DOWNTO 0));
end S28HL512TFPBHI010;
