-- generated by newgenasym Mon Jan 11 18:40:17 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity solder_bridge is
    port (    
	PIN1:      INOUT  STD_LOGIC;    
	PIN2:      INOUT  STD_LOGIC);
end solder_bridge;
