-- generated by newgenasym Tue Sep 25 10:19:38 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity single_row_3 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end single_row_3;
